name: flutter_sensor_compass
description: A plugin to get the orientation of the device (in degrees) relative to the magnetic north.
version: 1.0.0
author: Luis Andrés Jara Castillo <luisandres.jaracastillo@gmail.com>
homepage: https://github.com/LJaraCastillo/flutter_sensor_compass

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sensors: ^1.0.1
  vector_math: ^2.1.1

flutter:
